// jsonData.js
let json = `[{"id":1,"first_name":"Adelice","last_name":"Naden","email":"anaden0@vk.com","gender":"Female","salary":5140},
{"id":2,"first_name":"Stephie","last_name":"Brinkman","email":"sbrinkman1@msu.edu","gender":"Female","salary":6527},
{"id":3,"first_name":"Tawnya","last_name":"Raith","email":"traith2@npr.org","gender":"Female","salary":4740},
{"id":4,"first_name":"Wittie","last_name":"Bastin","email":"wbastin3@latimes.com","gender":"Male","salary":3039},
{"id":5,"first_name":"Danica","last_name":"Durdy","email":"ddurdy4@etsy.com","gender":"Female","salary":2840},
{"id":6,"first_name":"Nicole","last_name":"Pipworth","email":"npipworth5@illinois.edu","gender":"Female","salary":2757},
{"id":7,"first_name":"Kinsley","last_name":"Sarver","email":"ksarver6@altervista.org","gender":"Male","salary":7643},
{"id":8,"first_name":"Gretel","last_name":"Vearncombe","email":"gvearncombe7@discovery.com","gender":"Female","salary":3554},
{"id":9,"first_name":"Sandy","last_name":"Claeskens","email":"sclaeskens8@elpais.com","gender":"Male","salary":7170},
{"id":10,"first_name":"Alysa","last_name":"Hekkert","email":"ahekkert9@parallels.com","gender":"Female","salary":7551},
{"id":11,"first_name":"Erinna","last_name":"Wanley","email":"ewanleya@dmoz.org","gender":"Female","salary":7270},
{"id":12,"first_name":"Scarface","last_name":"Garrold","email":"sgarroldb@google.com.br","gender":"Male","salary":7922},
{"id":13,"first_name":"Cy","last_name":"Ramsey","email":"cramseyc@marketwatch.com","gender":"Male","salary":4423},
{"id":14,"first_name":"Isabelita","last_name":"Hamblin","email":"ihamblind@jalbum.net","gender":"Female","salary":2405},
{"id":15,"first_name":"Hillier","last_name":"Herkess","email":"hherkesse@toplist.cz","gender":"Male","salary":6838},
{"id":16,"first_name":"Alika","last_name":"Bratty","email":"abrattyf@purevolume.com","gender":"Female","salary":3926},
{"id":17,"first_name":"Ingelbert","last_name":"Penbarthy","email":"ipenbarthyg@exblog.jp","gender":"Male","salary":8895},
{"id":18,"first_name":"Quinn","last_name":"Werrett","email":"qwerretth@scribd.com","gender":"Female","salary":5552},
{"id":19,"first_name":"Jeanine","last_name":"Salvador","email":"jsalvadori@apple.com","gender":"Female","salary":8546},
{"id":20,"first_name":"Zebedee","last_name":"Piesold","email":"zpiesoldj@blinklist.com","gender":"Male","salary":5670}]`;